version: "3"
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=unleash
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
  unleash:
    image: unleashorg/unleash-server
    environment: 
      - DATABASE_URL=postgres://postgres:${POSTGRES_PASS}@postgres:5432/unleash
    restart: on-failure
    ports:
      - "4242:4242"
